In [1]:
import numpy as np

In [3]:
I = np.eye(3)

In [8]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
a = np.array([[1, 1, 2], [0, 0.5, 1], [0, 2, 1], [2, 1, 0]])

In [5]:
a.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [10]:
b = np.array([[1, 1, 2], [0, 0.5, 1], [0, 2, 1]])
np.linalg.inv(b)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [11]:
b

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])